# Site settings
title: Your awesome title
email: example@domain.com
description: "Test website"
baseurl: ""
url: "http://beckytodd.github.io"
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
permalink: pretty
